### ISSUE TITLE
Compatibility Issues with Next.js Integration

### ISSUE THREAD

**Issue by Rapshodus** [sereneinserenade/tiptap-comment-extension#10]
I am currently working on a Next.js project and have been trying to integrate the 'tiptap-comment-extension' . This extension has worked wonderfully in my React projects, and I'm eager to use its features in Next.js. However, I am encountering compatibility issues.

The specific problem arises when importing the extension into my Next.js project, which results in an internal server error. My suspicion is that this issue is related to Server-Side Rendering (SSR) in Next.js, as the extension was designed for a Vue or React environment.

I have checked the documentation and tried various approaches to resolve this, but have not been successful. I am reaching out for guidance or suggestions on adapting this extension for seamless integration with Next.js.

Here's a [codesandbox/replit reproduction](https://replit.com/join/ithbrvoecq-nkelava) of your React demo in Next.js.

**Comment by sereneinserenade** [comment]
Hey @Rapshodus thanks for reporting, fixed by 41f91521714540d27a2d0656d8fc0d1705d12214.

Please upgrate to new version `0.1.1` and use either of two.

```ts
import { CommentExtension } from "@sereneinserenade/tiptap-comment-extension";
// or
import CommentExtensionOrAnyOtherNameYouLike from "@sereneinserenade/tiptap-comment-extension";
```
