### ISSUE TITLE
Mark remains active when adding text or line break after highlighted comment

### ISSUE THREAD

**Issue by florianmascaro** [sereneinserenade/tiptap-comment-extension#18]
When I select some text and add a comment, and then add more text in the editor right after the highlighted word, the text I add is also underlined. The mark is still active. The same happens if I insert a line break.

**Comment by sereneinserenade** [comment]
Hey, extending Comment extension and adding `inclusive: false` should fix this.

```ts
Comment.extend({
  inclusive: false
}).configure({
  ...rest of configuration
})
```

**Comment by florianmascaro** [comment]
It works perfectly. Thanks 🙏

**Comment by florianmascaro** [comment]
It works perfectly. Thanks 🙏
