### ISSUE TITLE
Bug Report: select multiple blocks then add one comment, will generate duplicate comments.

### ISSUE THREAD

**Issue by jiangyijie27** [sereneinserenade/tiptap-comment-extension#3]
I understand what happens, because the comment `span` will be separated into multiple blocks.

![image](https://user-images.githubusercontent.com/7429808/164451448-5e6caf93-e1aa-438a-aad8-f5f58d467a37.png)

**Comment by jiangyijie27** [comment]
@sereneinserenade sorry, i've updated the img.

**Comment by sereneinserenade** [comment]
Yess, you're right, to tackle this, we'd have to use decorations!

**Comment by sereneinserenade** [comment]
@jiangyijie27 I'll be updating this repo soon with the implementation of comments with decorations

**Comment by chenyuncai** [comment]
maybe a comment node need a uniqueId to show once in right panel

**Comment by maryna-zinchenko** [comment]
As a temporary solution, you can add to your findCommentsAndStoreValues method this thing: 
`if (jsonComments !== null && !tempComments.find((el) => el.jsonComments.uuid === jsonComments.uuid)) {
          tempComments.push({
            node,
            jsonComments,
            from: pos,
            to: pos + (node.text?.length || 0),
            text: node.text
          })
        }`
