### ISSUE TITLE
The BubleMenu does not close immediately after the selection is reset

### ISSUE THREAD

**Issue by maryna-zinchenko** [sereneinserenade/tiptap-comment-extension#7]
### How to reproduce:
You can reproduce it here: https://sereneinserenade.github.io/tiptap-comment-extension/
1. Turn comments mode on
2. Select text (bubble menu will open)
3. Click anywhere on the text (bubble menu won't close)
4. Click anywhere on the text again (bubble menu will close)

### Possible solution: 
Add one more option to "should-show" bubble menu props: 
`:should-show="
  ({ editor, view, state, oldState, from, to }) =>
    isCommentModeOn &&
    !editor.state.selection.empty &&
    !activeCommentsInstance.uuid &&
    from !== to
            "`

**Comment by sereneinserenade** [comment]
Feel free to make a PR. This is just a demo site for the extension so it's not the main focus :-)
