### ISSUE TITLE
Missing MIT License file

### ISSUE THREAD

**Issue by kevlened** [sereneinserenade/tiptap-comment-extension#8]
Thanks for creating this, Jeet! The package.json indicates that this library has an MIT license, but there's no LICENSE file in the repo. The standard MIT license has a clause which includes:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software

Without a LICENSE file, it's unclear how to comply with the MIT license of this project.

I'm happy to open a PR for a LICENSE file if requested.

**Comment by kevlened** [comment]
In the interim, it seems the one here may be sufficient: https://github.com/sereneinserenade/tiptap-search-and-replace/blob/main/LICENSE

**Comment by sereneinserenade** [comment]
Hey @kevlened thanks for pointing out. Just created [licence](https://github.com/sereneinserenade/tiptap-comment-extension/blob/main/LICENSE) which is basically the same as https://github.com/sereneinserenade/tiptap-search-and-replace
